libsite/libwebsite/libapp/urls.py
from django.urls import path, include
from . import views
from django.views.generic.base import TemplateView


app_name = 'libapp' # for namespacing
urlpatterns = [
# do you need a path specific to submitting content via submit button?
    path('', views.index, name='index'),
    path('check/<int:bookpk>/', views.checkinout, name='checkout'),
    path('nobookforyou/', TemplateView.as_view(template_name = 'libapp/nobookforyou.html'), name='nobookforyou')
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

libsite/libwebsite/libwebsite/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libapp.urls')) # Note: all your app urls will start with this path
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

libsite/libwebsite/libapp/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models

url = models.CharField(max_length=100, unique=True)

class Author(models.Model):
	name = models.CharField(max_length=25, unique= True)

	pass
	def __str__(self):
		return self.name

class Book(models.Model):
	title = models.CharField(max_length=250, unique=True)
	pub_date = models.DateTimeField()
	author = models.ForeignKey(Author, on_delete=models.CASCADE)
	borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

	@property	
	def checked_out(self):
		last_checkout = self.liblists.last()
		if last_checkout:
			return last_checkout.checked_out
		else:
			return False
	
	@property
	def is_overdue(self):
		if self.due_back and date.today() > self.due_back:
			return True
		return False

	def __str__(self):
			return self.title

class Liblist(models.Model):
#take list out of the name lullz
	book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='liblists')
# ForeignKey: book (is this just book status? this ain't checkout status tbh
	member = models.ForeignKey(User, on_delete=models.CASCADE)
# foreignkey: we need to instantiate a userclass
	checked_out = models.BooleanField(default=True)
#true means the book  is NOT checked out yet
	date = models.DateTimeField(default=datetime.now())

	def toggle_checkout(self):
		self.checked_out = not self.checked_out

	def __str__(self):
		return 'Book: '+str(self.book)+', Member: '+str(self.member)+', Checked Out: '+str(self.checked_out)+', Date: '+str(self.date)
# checkout: models.Boolean

libsite/libwebsite/libapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import Book, Liblist


def index(request):
    # sub in models for libraries
    probablybooks = Book.objects.all() 
    checked_out_books = None
    if request.user.is_authenticated:
        checked_out_books = Book.objects.filter(borrower=request.user)
    return render(request, 'libapp/index.html', {'books':probablybooks, 'borrowlist':checked_out_books})


#build aout a context that links  Liblist to index


#assign the book to a user if there are no issues (manage issues as they come)
@login_required
def checkinout(request, bookpk): 
    book = get_object_or_404(Book, pk=bookpk)
    if book.checked_out:
        #member needs to be the latest
        member = book.borrower
        if request.user == member:
        #create a new entry to liblist for checking the book back in
            check_in = Liblist(book=book,member=request.user, checked_out=False)
            check_in.save()
            book.borrower = None
            book.save()
        else:
            return render(request, 'libapp/nobookforyou.html')
    else:
        check_out = Liblist(book=book,member=request.user, checked_out=True)
        check_out.save()
        book.borrower = request.user
        book.save()
    return redirect('libapp:index')



#assign book to user 

#last_checkout is a cross-section of liblists as asserted by book, 
#we need to assign a book to a user 
    

#     book_on_table.liblist_set.order_by('-date')
#     entries_in_liblist = Liblist.objects.filter(book=book_on_table).order_by('-date')
#     print(entries_in_liblist)
#     if entries_in_liblist.exists():
#         entry = entries_in_liblist[0]
#         if Liblist.objects.filter(status=bookcheckoutstatus).exists(False):
#         #is the book on the checkout list?
#             return 404
#         if Liblist.objects.filter(member = member).exists():
#             return 404
#         else check out book
#     else:
#         some other logic
# oes book exist in libslit
#     if checkoutstatus in model returns true
#     if member in model returns true (as in member field isn't null) AND if the member is not x return 
        


# once connected, check if the title's entry in database for book checkoutstatus:
#if checked out, return fuck off, else check out
    return HttpResponse(bookpk)



#check-out view (post): takea  book out of the library and assign to user,take a book out of the library and put it in the user's checkout list
#check-in view (post): return a book to the library and take it off of the user's checkout list
#under a user's record list books they take out, add a book to the user's record


#figure out what andi how you need to wire it
#model connect
#template connect

#do check-in and check-out need unique and individual defs if they're both playing off of the same system?

# def with book data, lookup in db and see if it's available then fork yes/no 
# (yes for checkin)
# no for checkout

libsite/libwebsite/libapp/templates/libapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Some Library</title>
  {% load static %}

  <link rel="stylesheet" type="text/css" href="{% static 'urlapp/style.css' %}" />
</head>

<body>

<ul>
{% for book in books %}
  <li>
    {{ book }}
    <a href="{% url 'libapp:checkout' bookpk=book.pk %}">
    
    {% if user.is_authenticated %}
      {% if book.borrower == user %}
          <button type="submit">Check-in</button>
      {% elif book.checked_out == False %}
          <button type="submit">Check-out</button>
      {% endif %}
    {% endif %}
    </a>
  </li>
{% endfor%}
</ul>

{# the following list is to show books the user has registered under their name  #}
<ul>
    <ul>checked out books</ul>
    {% for book in borrowlist %}
    <ul>{{ book }}</ul>
    {% endfor %}
</ul>

  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 
  </ul>

</body>

</html>

libsite/libwebsite/libapp/templates/libapp/nobookforyou.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
</head>
<body>
    <h1>NOBOOK FOR YOUUU</h1>
    <hr/>
    {% block content %}
    {% endblock %}
    <hr/>
</body>

libsite/libwebsite/templates/base_generic.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
</head>
<body>
    <ul class ="sidebar-nav">
    {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
   {% else %}
     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
   {% endif %} 
  </ul>
    	
    <h1>{% block title %}{% endblock %}</h1>
    <hr/>
    {% block content %}
    {% endblock %}
    <hr/>
    (c) myapp inc
</body>